export {
  applyFirstTypaiCodeMirrorRedSuggestion,
  clearTypaiCodeMirrorGhostText,
  clearTypaiCodeMirrorMarks,
  closeTypaiCodeMirrorPopover,
  getTypaiCodeMirrorGhostTextContent,
  getTypaiCodeMirrorViewMarks,
  getTypaiCodeMirrorViewTransactions,
  ignoreFirstTypaiCodeMirrorRedMark,
  isTypaiCodeMirrorGhostTextVisible,
  openFirstTypaiCodeMirrorBluePopover,
  openFirstTypaiCodeMirrorRedPopover,
  openTypaiCodeMirrorPopoverForMark,
  renderTypaiCodeMirrorGhostText,
  revertFirstTypaiCodeMirrorCorrection,
  revertSelectedTypaiCodeMirrorCorrection,
} from "./commands";
export { createTypaiCodeMirrorExtension } from "./createTypaiCodeMirrorExtension";
export {
  typaiCodeMirrorBlueCorrectedClass,
  typaiCodeMirrorGhostTextClass,
  typaiCodeMirrorRedSpellingClass,
} from "./decorations";
export {
  clearTypaiCodeMirrorGhostTextEffect,
  getTypaiCodeMirrorGhostText,
  getTypaiCodeMirrorMarks,
  getTypaiCodeMirrorOptions,
  getTypaiCodeMirrorRuntimeSettings,
  getTypaiCodeMirrorTransactions,
  setTypaiCodeMirrorGhostTextEffect,
  setTypaiCodeMirrorRuntimeSettingsEffect,
  typaiCodeMirrorGhostTextField,
  typaiCodeMirrorMarksField,
  typaiCodeMirrorOptionsFacet,
  typaiCodeMirrorRuntimeSettingsField,
  typaiCodeMirrorTransactionsField,
} from "./state";
export type {
  CodeMirrorCompletionController,
  CodeMirrorCompletionEditor,
  CodeMirrorCompletionGhost,
  CodeMirrorCompletionGhostMetadata,
  CodeMirrorCompletionMode,
  CodeMirrorCompletionSnapshot,
  CodeMirrorGhostTextClearReason,
  CodeMirrorTypaiCorrectionTransaction,
  CodeMirrorTypaiCorrectionTrigger,
  CodeMirrorTypaiMark,
  TypaiCodeMirrorCorrectionEvent,
  TypaiCodeMirrorDecisionEvent,
  TypaiCodeMirrorMarkKind,
  TypaiCodeMirrorOptions,
} from "./types";
